name: Build ESPhub Firmware

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    if: contains(github.event.head_commit.message, 'Build')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (incluyendo submódulos)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Instalar dependencias
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi build-essential cmake git

      - name: Compilar firmware con compile.sh
        run: |
          # chmod +x ./compile.sh
          # ./compile.sh
          echo "PICO_SDK_PATH ha sido configurado a $PICO_SDK_PATH"
          PROJECT_DIR="."
          BUILD_DIR="$PROJECT_DIR/build"
          if [ -d "$BUILD_DIR" ]; then
              echo "Eliminando el directorio build..."
              rm -rf "$BUILD_DIR"
              echo "Directorio build eliminado."
          else
              echo "El directorio build no existe."
          fi

          mkdir $BUILD_DIR
          cd $BUILD_DIR

          cmake -Wno-dev -DCMAKE_BUILD_TYPE=Debug .. 
          make
      - name: Subir esphub.uf2
        uses: actions/upload-artifact@v4
        with:
          name: esphub.uf2
          path: build/esphub.uf2

      - name: Subir esphub.elf
        uses: actions/upload-artifact@v4
        with:
          name: esphub.elf
          path: build/esphub.elf